version: "3"
services:
  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181
  
  chatee-kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=10.23.45.34:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://10.23.45.34:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
